"""create career assessments table

Revision ID: e7c3134b5b4f
Revises: 19ce1974eff2
Create Date: 2026-09-17 14:59:16.917003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c3134b5b4f'
down_revision: Union[str, Sequence[str], None] = '19ce1974eff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('responses', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_assessments_id'), 'career_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_career_assessments_user_id'), 'career_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_assessments_user_id'), table_name='career_assessments')
    op.drop_index(op.f('ix_career_assessments_id'), table_name='career_assessments')
    op.drop_table('career_assessments')
    # ### end Alembic commands ###
