"""create career skills table

Revision ID: f1e3044ef88f
Revises: 507fc4a34be0
Create Date: 2026-09-17 14:44:20.749040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e3044ef88f'
down_revision: Union[str, Sequence[str], None] = '507fc4a34be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'skill_id', name='uq_career_skill')
    )
    op.create_index(op.f('ix_career_skills_career_id'), 'career_skills', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_skills_id'), 'career_skills', ['id'], unique=False)
    op.create_index(op.f('ix_career_skills_skill_id'), 'career_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_skills_skill_id'), table_name='career_skills')
    op.drop_index(op.f('ix_career_skills_id'), table_name='career_skills')
    op.drop_index(op.f('ix_career_skills_career_id'), table_name='career_skills')
    op.drop_table('career_skills')
    # ### end Alembic commands ###
